services:
  mysql:
    image: mysql:lts
    container_name: serverless-mysql-test-db
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: serverless_mysql_test
      MYSQL_USER: testuser
      MYSQL_PASSWORD: testpassword
      # Allow connections from any host
      MYSQL_ROOT_HOST: "%"
      TZ: UTC
    ports:
      - "3306:3306"
    command: >
      --max_connections=1000
      --wait_timeout=28800
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 5s
      retries: 10
