name: "Integration Tests"
on:
  pull_request:
    types: [opened, reopened, synchronize]
  push:
    branches:
      - master

# This workflow runs integration tests with a MySQL database
# For more information on contributing and testing, see CONTRIBUTING.md

jobs:
  integration-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [18, 20, 22]
    name: Node ${{ matrix.node }} Integration Tests

    services:
      # MySQL service container
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: test
        ports:
          - 3306:3306
        # Set health checks to wait until MySQL has started
        options: >-
          --health-cmd="mysqladmin ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
      - name: "Checkout latest code"
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Set up node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}

      - name: Install dependencies
        run: npm ci

      - name: Run unit tests
        run: npm run test:unit

      - name: Run integration tests
        run: npm run test:integration
        env:
          MYSQL_HOST: localhost
          MYSQL_PORT: 3306
          MYSQL_DATABASE: test
          MYSQL_USER: root
          MYSQL_PASSWORD: password

      - name: Run all tests with coverage
        if: matrix.node == 22
        run: npm run test-cov
        env:
          MYSQL_HOST: localhost
          MYSQL_PORT: 3306
          MYSQL_DATABASE: test
          MYSQL_USER: root
          MYSQL_PASSWORD: password
